import Link from "next/link";

const HomePage = () => {
  return (
    <main className="bg-gray-50 min-h-screen">
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-blue-500 to-purple-600 text-white py-16 px-4 text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to Food Recipe AI</h1>
        <p className="text-lg mb-6">
          Your personal assistant for generating food recipes, analyzing
          nutrition, and creating shopping lists!
        </p>
        <Link
          href="/register"
          className="bg-yellow-400 text-gray-900 px-6 py-3 rounded-md text-lg font-semibold hover:bg-yellow-300 transition"
        >
          Get Started
        </Link>
      </div>

      {/* About Section */}
      <div className="max-w-6xl mx-auto py-12 px-4">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">About the Project</h2>
        <p className="text-gray-700 text-lg leading-7 mb-6">
          Food Recipe AI is a cutting-edge application powered by AI and
          seamless backend integration. It allows users to generate customized
          food recipes, analyze the nutritional information of their meals, and
          even create a shopping list tailored to their favorite recipes. With
          advanced features like image uploading and AI-based recommendations,
          this tool is designed to make your cooking experience easy and fun.
        </p>
      </div>

      {/* How It Works Section */}
      <div className="bg-white py-12 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">How It Works</h2>
          <ul className="list-decimal pl-5 text-gray-700 text-lg leading-8">
            <li>Register or login to your account to access all features.</li>
            <li>Upload an image of ingredients or enter a list of items.</li>
            <li>Get a detailed recipe generated by AI.</li>
            <li>Analyze the nutritional value of your meals.</li>
            <li>Create a shopping list for your selected recipes.</li>
          </ul>
        </div>
      </div>

      {/* Call to Action */}
      <div className="bg-gray-100 py-8 text-center">
        <h3 className="text-lg font-medium text-gray-800 mb-4">
          Ready to explore delicious recipes?
        </h3>
        <Link
          href="/register"
          className="bg-blue-600 text-white px-6 py-3 rounded-md font-semibold hover:bg-blue-500 transition"
        >
          Start Your Journey
        </Link>
      </div>
    </main>
  );
};

export default HomePage;
