"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Autoplay } from "swiper/modules";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Image from "next/image";
import { FaUserPlus, FaUpload, FaUtensils, FaAppleAlt, FaShoppingCart } from "react-icons/fa";

const HomePage = () => {
    const dishes = [
        { src: "/Images/1ff7362d-341d-4a3c-83d5-dc1a9a67dd2b-removebg-preview.png", alt: "Pizza" },
        { src: "/images/tikka-removebg-preview.png", alt: "Chicken Tikka" },
        { src: "/images/rice.jpeg", alt: "Fries" },
    ];

    const steps = [
        { icon: <FaUserPlus />, text: "Register or login to your account to access all features." },
        { icon: <FaUpload />, text: "Upload an image of ingredients or enter a list of items." },
        { icon: <FaUtensils />, text: "Get a detailed recipe generated by AI." },
        { icon: <FaAppleAlt />, text: "Analyze the nutritional value of your meals." },
        { icon: <FaShoppingCart />, text: "Create a shopping list for your selected recipes." },
    ];

    return (
        <main className="bg-gray-50 min-h-screen">
            {/* Hero Section */}
            <div className="bg-gradient-to-r from-orange-500 to-red-500 text-white py-16 px-4 text-center">
                <motion.h1
                    className="text-4xl md:text-6xl font-bold mb-4"
                    initial={{ opacity: 0, y: -50 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 1 }}
                >
                    Welcome to Food Recipe AI
                </motion.h1>
                <motion.p
                    className="text-lg md:text-xl mb-8"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.5, duration: 1 }}
                >
                    Your personal assistant for generating food recipes, analyzing nutrition, and creating shopping lists!
                </motion.p>
                <Swiper
                    modules={[Navigation, Pagination, Autoplay]}
                    spaceBetween={20}
                    slidesPerView={1}
                    navigation
                    pagination={{ clickable: true }}
                    autoplay={{ delay: 3000 }}
                    className="w-full max-w-md mx-auto"
                >
                    {dishes.map((dish, index) => (
                        <SwiperSlide key={index}>
                            <motion.div
                                className="relative w-64 h-64 mx-auto"
                                animate={{ rotate: 360 }}
                                transition={{ duration: 10, repeat: Infinity, ease: "linear" }}
                            >
                                <Image
                                    src={dish.src}
                                    alt={dish.alt}
                                    width={256}
                                    height={256}
                                    className="object-contain rounded-full "
                                />
                            </motion.div>
                        </SwiperSlide>
                    ))}
                </Swiper>
                <Link
                    href="/register"
                    className="mt-8 inline-block bg-yellow-400 text-gray-900 px-6 py-3 rounded-md text-lg font-semibold hover:bg-yellow-300 transition"
                >
                    Get Started
                </Link>
            </div>

            {/* About Section */}
            <div className="max-w-6xl mx-auto py-12 px-4 flex flex-col md:flex-row items-center">
                <div className="md:w-1/2">
                    <h2 className="text-2xl font-bold text-gray-800 mb-4">About the Project</h2>
                    <p className="text-gray-700 text-lg leading-7 mb-6">
                        Food Recipe AI is a cutting-edge application powered by AI and seamless backend integration. It allows users to generate customized food recipes, analyze the nutritional information of their meals, and even create a shopping list tailored to their favorite recipes. With advanced features like image uploading and AI-based recommendations, this tool is designed to make your cooking experience easy and fun.
                    </p>
                </div>
                <motion.div
                    className="md:w-1/2 p-4"
                    whileHover={{ scale: 1.05 }}
                    transition={{ duration: 0.3 }}
                >
                    <Image
                        src="/images/1cmzKlJIMkZ0olUKgso14hJbptmjzuSKX6k9iIim.webp"
                        alt="Spices"
                        width={600}
                        height={600}
                        className="rounded-lg shadow-md"
                    />
                </motion.div>
            </div>

            {/* How It Works Section */}
            <div className="bg-white py-12 px-4">
                <div className="max-w-6xl mx-auto">
                    <h2 className="text-2xl font-bold text-gray-800 mb-8 text-center">How It Works</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {steps.map((step, index) => (
                            <motion.div
                                key={index}
                                className="bg-gray-100 p-6 rounded-lg shadow-md hover:shadow-lg transition"
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: index * 0.2, duration: 0.5 }}
                            >
                                <div className="text-orange-500 text-3xl mb-4">{step.icon}</div>
                                <p className="text-gray-700 text-lg">{step.text}</p>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Call to Action */}
            <div
                className="bg-cover bg-center py-12 text-center"
                style={{ backgroundImage: "url('/images/ai-generated-8483628.jpg')" }}
            >
                <div className="bg-black bg-opacity-50 py-8">
                    <h3 className="text-lg font-medium text-white mb-4">
                        Ready to explore delicious recipes?
                    </h3>
                    <Link
                        href="/register"
                        className="bg-blue-600 text-white px-6 py-3 rounded-md font-semibold hover:bg-blue-500 transition"
                    >
                        Start Your Journey
                    </Link>
                </div>
            </div>
        </main>
    );
};

export default HomePage;